# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Root
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"

  # Infrastructure
  - package-ecosystem: 'npm'
    directory: '/infrastructure'
    groups:
      infrastructure:
        patterns:
          - "*"
    schedule:
      interval: 'weekly'  

  # Bootstrap
  - package-ecosystem: 'npm'
    directory: '/bootstrap'
    groups:
      bootstrap:
        patterns:
          - "*"
    schedule:
      interval: 'weekly'  